title: Julien Leparoux # your name (or website title) here
logo: "/images/my_id.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research engineer in Fluid Mechanics.
  - Senior Python developer (5+ years of experience) 
  - Data Scientist (2+ years of experience)
  <br><br>
  Passionate about technology and innovation around scientific computing, data exploration and data analysis. I am driven by the efficiency in industrial topics to meet project needs (data processing, experimental design, data visualization, modeling, ...).
  <br><br>
  <a href="https://www.linkedin.com/in/julien-leparoux-71629633/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
